### ISSUE TITLE
Syntax highlighting for cell magic?

### ISSUE THREAD

**Issue by wcooley** [lebedov/icypher#1]
It would be nice if icypher could enable syntax-highlighting for _%%cypher_ cell magic. Currently it seems that CodeMirror uses syntax for Python.

I'm not entirely sure it's possible or what would be required; I researched and found a notebook issue for _%%ruby_ magic that seems generally applicable (jupyter/notebook/issues/2102). I asked in _jupyter/notebook_ on gitter but got no reply. It's possible that in addition to the magic class you'd also have to create a kernel, such as described in [Making simple Python wrapper kernels
](https://jupyter-client.readthedocs.io/en/latest/wrapperkernels.html).

I do know, however, that CodeMirror itself has syntax support for Cypher -- create a text file from the tree and "Cypher" is available in the languages list (and works).

**Comment by lebedov** [comment]
[Some folks](http://stackoverflow.com/a/43644349) do indeed appear to have activated syntax highlighting for other CodeMirror-supported languages in Jupyter notebook cells, but only in notebook 4.x. Let's see what the Jupyter developers [say](https://github.com/jupyter/notebook/issues/2453).

**Comment by lebedov** [comment]
Thanks to feedback from @takluyver, I found out how to activate syntax highlighting for SQL in notebook 5.x; however, I still [haven't gotten cypher highlighting to activate](https://github.com/jupyter/notebook/issues/2462).

**Comment by wcooley** [comment]
Thanks for looking at this!

With the snippet in `custom.js`, it looks like it is indeed working -- the highlighting is the same compared with editing a text file in Notebook with type set to "Cypher". If I change `%%cypher` to something else so the highlighting changes, then back to `%%cypher`, I get the highlighting that again matches the Notebook/CodeMirror text editor.

(The highlighting seems a little off, but that's a CodeMirror issue. For example, a named identifier with a node label/relationship type in a `MATCH` clause is highlighted, both with the same color, but only when there both a named identifier and label/type is present--use only a named identifier or label/type and there is no highlight.)

My next question is whether this can be done automatically when the extension is loaded or does that require a custom language kernel?

**Comment by lebedov** [comment]
Strange..not sure why it doesn't seem to be working for me. I updated icypher to activate Cypher syntax highlighting when loaded. Let me know if the latest revision on GitHub works for you.

**Comment by wcooley** [comment]
... and here's where I put my foot in my mouth because I realize I'm actually using _ipython-cypher_, not _icypher_, because my codebase is still mired in _py2neo_ 1.6. That said, supporting 1.6 would be fairly trivial in this case (I've been thinking about extracting some of the compatibility work I've done for _py2neo_ into a standalone package, but that would probably be overkill here).

However, the highlighting in the images in jupyter/notebook#2462 match what I see in the Notebook/CodeMirror text editor when the language is set to "Cypher", so I think that's correct.

**Comment by lebedov** [comment]
But does the highlighting change when one enters Cypher into a cell without `%%cypher`?

**Comment by lebedov** [comment]
Mystery solved - there was a `~/.jupyter/nbconfig/notebook.json` file in place that was already activating cypher mode for `%%cypher` cells. The modification made to icypher therefore works as desired - I'll upload a new release to pypi later.

**Comment by lebedov** [comment]
New release up.
