### ISSUE TITLE
IPython.config deprecated when loading icypher 

### ISSUE THREAD

**Issue by samdeleu** [lebedov/icypher#3]
Hi, I installed the icypher extension, but when i do a:

**%load_ext icypher**

I get the message:
**.../jupyter/lib/python3.6/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)**

Any idea how i can solve this?

Thanks

**Comment by lebedov** [comment]
Fixed.
